// examples/tanstack/start-solid/src/gallery.tsx
import { createFileRoute, Link } from '@tanstack/solid-router';
import { For } from 'solid-js';

export const Route = createFileRoute('/')({
	component: Gallery,
});

const sections = [
	{
		label: 'Managing State',
		children: [
			{ to: '/stale-closures', label: 'Stale Closures' }, //
		],
	},
	{
		label: 'Concurrent Rendering',
		children: [
			{ to: '/transition-signal', label: 'useTransition with createSignal' }, //
		],
	},
];

function Gallery() {
	return (
		<div class="mx-2 my-1 flex flex-col gap-4">
			<For each={sections}>
				{(section) => {
					return (
						<div class="flex flex-col">
							<div>
								<span class="bg-[#ffdd00]">{section.label}</span>
							</div>
							<For each={section.children}>
								{(child) => {
									return <Link to={child.to}>{child.label}</Link>;
								}}
							</For>
						</div>
					);
				}}
			</For>
		</div>
	);
}

// examples/tanstack/start/src/Gallery.tsx
import { Link } from '@tanstack/react-router';

export const Route = createFileRoute({
  component: RouteComponent,
});

const sections = [
  {
    label: 'Managing State',
    children: [
      { to: '/stale-closures', label: 'Stale Closures' }, //
    ],
  },
  {
    label: 'Concurrent Rendering',
    children: [
      { to: '/transition-use-state', label: 'useTransition with useState' },
      { to: '/transition-use-context-selector', label: 'useTransition with useContextSelector' },
      { to: '/transition-use-search', label: 'useTransition with useSearch' },
      { to: '/transition-redux', label: 'useTransition with Redux' },
      { to: '/transition-zustand', label: 'useTransition with Zustand' },
    ],
  },
];

function RouteComponent() {
  return (
    <div className="mx-2 my-1 flex flex-col gap-4">
      {sections.map((section, idx) => {
        return (
          <div key={idx} className="flex flex-col">
            <div>
              <span className="bg-[#ffdd00]">{section.label}</span>
            </div>
            {section?.children?.map((child, idx) => {
              return (
                <Link key={idx} to={child.to}>
                  {child.label}
                </Link>
              );
            })}
          </div>
        );
      })}
    </div>
  );
}
